// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantRater.Models;

#nullable disable

namespace RestaurantRater.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231220231304_BowserChilliAndRating")]
    partial class BowserChilliAndRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantRater.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("CleanlinessScore")
                        .HasColumnType("float");

                    b.Property<double>("EnvironmentScore")
                        .HasColumnType("float");

                    b.Property<double>("FoodScore")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CleanlinessScore = 10.0,
                            EnvironmentScore = 8.8000000000000007,
                            FoodScore = 7.5,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 2,
                            CleanlinessScore = 9.9000000000000004,
                            EnvironmentScore = 9.8000000000000007,
                            FoodScore = 8.5,
                            RestaurantID = 1
                        },
                        new
                        {
                            ID = 3,
                            CleanlinessScore = 10.0,
                            EnvironmentScore = 5.7999999999999998,
                            FoodScore = 3.5,
                            RestaurantID = 2
                        },
                        new
                        {
                            ID = 4,
                            CleanlinessScore = 7.0,
                            EnvironmentScore = 6.7999999999999998,
                            FoodScore = 6.5,
                            RestaurantID = 2
                        });
                });

            modelBuilder.Entity("RestaurantRater.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "1Up Lane",
                            Name = "Super Mario Pasta Cavern"
                        },
                        new
                        {
                            ID = 2,
                            Address = "123 GRRRR Court",
                            Name = "Bowsers Hot Chilli Shop!"
                        });
                });

            modelBuilder.Entity("RestaurantRater.Models.Rating", b =>
                {
                    b.HasOne("RestaurantRater.Models.Restaurant", "Restaurant")
                        .WithMany("Ratings")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantRater.Models.Restaurant", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
